project:
  type: website

website:
  title: "ailearningloop"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lukmanaj
      - icon: twitter
        href: https://twitter.com/lukmanajjk
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto


