project:
  type: website

website:
  title: "ailearningloop"
  site-url: "https://lukmanaj.github.io/ailearningloop/"
  description: "Venturing Beyond My Roots: An AI Odyssey Unfolds for This Non-Tech Trailblazer!"
  margin-header: subscribe.html
  comments: 
    utterances:
      repo: quarto-dev/quarto-web
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lukmanaj
      - icon: twitter
        href: https://twitter.com/lukmanajjk
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto


