project:
  type: website

website:
  title: "ailearningloop"
  site-url: "https://lukmanaj.github.io/ailearningloop/"
  description: "Venturing Beyond My Roots: An AI Odyssey Unfolds for This Non-Tech Trailblazer!"
  google-analytics: "G-J7BWRJYLX5"
  comments: 
    utterances:
      repo: lukmanaj/ailearningloop
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lukmanaj
      - icon: twitter
        href: https://twitter.com/lukmanajjk
      - icon: linkedin
        href: https://linkedin.com/in/lukman-a-j
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto


