---
title: "Joining The First Cohort of the Arewa Data Science Academy Fellowship"
author: "Lukman Aliyu Jibril"
date: "2023-02-14"
categories: [arewads]
---
The application link for the fellowship was sent to me by my friend, Abbas. Reluctantly, I opened it, only to be surprised by the requirement to complete an introduction to Python course on Udacity. Uploading the course certificate was mandatory. After completing the course, I discovered that obtaining the certificate required payment. To overcome this, I took a screenshot of my course dashboard showing my completion and uploaded that instead. A few days later, I received an email confirming my acceptance. This marked the beginning of my Python journey. Before joining Arewa, my experience with Python was purely theoretical, and I didn’t have an IDE installed on my laptop. I used Colab occasionally for practice.

After joining Arewa, I was encouraged to install VSCode and practice daily. Our mentor, Shamsuddeen, often emphasizes the importance of atomic habits, inspired by James Clear’s famous book. Having an IDE on my laptop and a structured course with daily exercises has significantly improved my understanding and appreciation of Python.

Our Arewa Data Science Fellowship officially began on January 23, 2023, with Phase One of four phases, which includes:

- 30 Days of Python Challenge: Designed to enhance our Python skills in preparation for Machine Learning and Deep Learning with PyTorch.
- Coursera Course 'Learning How to Learn': Aimed at improving our learning efficiency due to the numerous concepts in data science.
- Git and GitHub: For version control and collaboration.
- Blogging: To document our learning journey, which is why I am here.


The fellowship is structured for self-paced learning, complemented by twice-weekly office hours with mentors on weekends to clarify concepts and discuss challenges encountered during exercises.

I will share more about the fellowship as I delve into various subjects in my programming journey with Arewa Data Science Academy.

> Practice makes improvement and possible mastery. This is my take home from my first few weeks in this fellowship. Practice is what I have been missing in my learning journey. As such, it is a great pleasure to be part of the first cohort of this fellowship. In sha Allah, greatness awaits.
