---
title: "Becoming a Devotee: The Power of Streaks"
author: "Lukman Aliyu Jibril"
date: "2024-08-19"
categories: [deeplearning-ai]
draft: true
---


And I finally became a Devotee at the DeepLearning.AI forum. Becoming a devotee is no mean feat. It requires showing up to the forum every single day for 365 days straight. With the grace of Allah, I was able to achieve that. To appreciate this, it must be understood that missing just a single day can ruin it. Let's say you miss day 300, then you are now on a 65 days streak. It's that bad.

I have been hoping for this for a while. Ever since I achieved the 100 days streak badge (afficionado). Since it is a discourse forum, we have a 10 day streak (enthusiast), followed by a 100 day streak and then a 365 day or one-year streak. At the moment, I have achieved all three. The interesting thing is that I am only the 5th to achieve this in over four years. The rest are long-time forum elders. 

I have been on several streaks in recent times. I have active streaks in DataCamp(196 days), Github(250+ days) and of course DeepLearning.AI forum (365 days). I want to build atomic habits that will directly lead to my growth. I have to grow so that I will be worthy of the big things I am currently pursuing. 

In sha Allah, I will continue to utilize my time in potentially productive endeavours and reduce my social media usage. The goal is to be aggressive in my pursuit of professional development. Going forward, I will be super serious in my targets. O Allah, guide and direct all my affairs. Alhamdulillah.  